version: '3.9'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
#    network_mode: host
#    networks:
#      - localprom
    restart: unless-stopped

#  nats:
#    image: nats:2.11.4-alpine
#    container_name: nats-js
#    ports:
#      - "4222:4222"  # NATS client connections
#      - "8222:8222"  # Monitoring endpoint (HTTP)
#    command: >
#      -js
#      -m 8222
#      -sd /data/jetstream
#    volumes:
#      - ./nats-data:/data/jetstream

networks:
  localprom:
    driver: bridge