logging.config: classpath:log4j2-spring.yaml

spring:
  output:
    ansi:
      enabled: ALWAYS

iso:
  console-handler-info:
    channel-name: shetab-7-ascii-channel-v93
    packager-type: shetab-7-ascii-v93
    header-provider-bean: shetab-7-iso-header-provider
    header-processor-bean: shetab-7-iso-header-processor
    message-handler-bean: isoMessageRequestHandler
    log-hex-in-out: true

#  channel-info:
#    name: shetab-7-ascii-channel-v93
#    iso-channel-type: ascii
#    ascii-header-detail:
##      iso-header-type: none
#      iso-header-type: variable
#      len-digits: 4
##      iso-header-type: not-separated-from-the-message
#    ascii-detail:
#      total-len-digits: 4

  channel-info-conf:
    enabled: true
    channelInfos:
      - name: shetab-7-ascii-channel-v93
        iso-channel-type: ascii
        ascii-header-detail:
          iso-header-type: variable
          len-digits: 4
        ascii-detail:
          total-len-digits: 4
      - name: non-header-shetab-7-ascii-channel-v93
        iso-channel-type: ascii
        ascii-header-detail:
          iso-header-type: none
        ascii-detail:
          total-len-digits: 4

  client-info-conf:
    enabled: true
    isoClientInfos:
      - host: localhost
        port: 1023
#        socketConnectionType: one-time
        socketConnectionType: after-idle-timeout
        durationInMillis: 10000
        match-key-provider-bean: shetab-7-match-key-provider
        channel-name: non-header-shetab-7-ascii-channel-v93
        packager-type: shetab-7-ascii-v93
#        packager-type: binary-v87
#        response-header-provide-type: provide-from-handler
#        header-provider-bean: shetab-7-iso-header-provider
#        handler-bean: shetab-7-payload-handler
        logHexOutIn: true
